services:
  db:
    image: 'mysql:8.4.5'
    environment:
      MYSQL_ROOT_PASSWORD: '${DEMO_DB_PASSWORD}'
      MYSQL_DATABASE: '${DEMO_DB_DATABASE}'
    volumes:
      - type: 'volume'
        source: 'db_data02'
        target: '/var/lib/mysql'
      - type: 'bind'
        source: './db/initdb.d'
        target: '/docker-entrypoint-initdb.d'
        read_only: true
    networks:
      - 'demo-nw02'

  app:
    image: 'demo-app:0.1.0'
    build:
      context: './app'
      args:
        IMAGE_TAG: '3.13.5-slim-bookworm'
    environment:
      DB_USER: '${DEMO_DB_USER}'
      DB_PASSWORD: '${DEMO_DB_PASSWORD}'
      DB_SCHEMA: '${DEMO_DB_DATABASE}'
    expose:
      - '8000'
    networks:
      - 'demo-nw02'
    depends_on:
      - 'db'

  nginx:
    image: nginx:1.28.0-bookworm
    ports:
      - "80:80"
    volumes:
      - './nginx/default.conf:/etc/nginx/conf.d/default.conf:ro'
    networks:
      - 'demo-nw02'
    depends_on:
      - 'app'

volumes:
  db_data02:
    name: 'db_data02'

networks:
  demo-nw02:
    driver: 'bridge'

